FROM amazonlinux:latest
MAINTAINER gopi gopi@gmail.com
RUN yum update -y && \
    yum install -y java-1.8.0-openjdk wget && \
    yum clean all
RUN useradd -m jenkins
WORKDIR /opt/jenkins
RUN wget https://get.jenkins.io/war-stable/latest/jenkins.war
EXPOSE 8080 50000
CMD ["java", "-jar", "jenkins.war"]
